import { generateMfaSecret, verifyMfaToken, generateMfaQrCode } from '../lib/mfa';
import { authenticator } from 'otplib';

// Note: lib/mfa.ts uses 'new TOTP(...)'. verifyMfaToken uses 'verifySync'.
// We need to ensure that the token generated by the same config (period 30, digits 6) works.

// We can use a temporary TOTP instance to generate a valid token for testing
// since 'active' authenticator is not exported from lib/mfa.ts (it is not exported).
// But generateMfaSecret uses it.
// And we need verifyMfaToken to work with tokens generated by compatible apps (like Google Auth).

import { TOTP } from 'otplib';

async function runTest() {
    console.log("Starting MFA Fix Verification...");

    // 1. Generate Secret using the real function
    const secret = generateMfaSecret();
    console.log("Generated Secret:", secret);

    // 2. Generate a valid token manually using compatible settings
    // lib/mfa.ts uses period 30, digits 6 (defaults for Google Auth)
    // verifySync uses defaults (period 30, digits 6)
    const tempAuthenticator = new TOTP({
        period: 30,
        digits: 6
    });

    const validToken = tempAuthenticator.generate(secret);
    console.log("Generated Valid Token:", validToken);

    // 3. Verify Valid Token
    console.log("Verifying Valid Token...");
    const isValid = verifyMfaToken(validToken, secret);
    console.log(`Result for Valid Token: ${isValid}`); // Expected: true

    if (isValid === true) {
        console.log("✅ SUCCESS: Valid token accepted.");
    } else {
        console.error("❌ FAILURE: Valid token rejected.");
        // Debug info
        console.log("Ensure system time is correct. Code generated at:", new Date().toISOString());
    }

    // 4. Verify Invalid Token
    const invalidToken = "000000";
    console.log(`Verifying Invalid Token (${invalidToken})...`);
    const isInvalid = verifyMfaToken(invalidToken, secret);
    console.log(`Result for Invalid Token: ${isInvalid}`); // Expected: false

    if (isInvalid === false) {
        console.log("✅ SUCCESS: Invalid token rejected.");
    } else {
        console.error("❌ FAILURE: Invalid token accepted.");
    }

    // 5. Check QrCode generation (just to ensure no breakages)
    try {
        const qr = generateMfaQrCode("test@example.com", secret);
        console.log("QR Code URI generated successfully:", qr.substring(0, 20) + "...");
    } catch (e) {
        console.error("❌ FAILURE: QR Code generation failed:", e);
    }
}

runTest();
